In [136]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
sys.path.append(os.path.abspath(os.path.join('..')))
import src.exploration as e
import src.transform as t

In [137]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [138]:
df_data = pd.read_csv("../files/raw/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [139]:
df_data = t.standardize_columns(df_data)

In [140]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_email,customer_fname,customer_id,customer_lname,customer_password,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,market,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
103867,PAYMENT,4,4,59.500000,169.990005,Shipping on time,0,48,Water Sports,Virginia Beach,EE. UU.,XXXXXXXXX,Mary,1289,Dominguez,XXXXXXXXX,Home Office,VA,1795 Fallen Corners,23454.0,7,Fan Shop,36.843868,-76.033806,Europe,Miramas,Francia,1289,8/14/2015 20:31,15473,1073,30.00,0.15,38671,199.990005,0.35,1,199.990005,169.990005,59.500000,Western Europe,Provenza-Alpes-Costa Azul,PENDING_PAYMENT,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,8/18/2015 20:31,Standard Class
36017,DEBIT,2,1,-539.969971,299.989990,Late delivery,1,45,Fishing,Dallas,EE. UU.,XXXXXXXXX,Patricia,2591,Smith,XXXXXXXXX,Consumer,TX,6940 Pleasant Zephyr Via,75231.0,7,Fan Shop,32.854767,-96.739975,Europe,Almelo,Países Bajos,2591,6/16/2015 17:38,11423,1004,100.00,0.25,28572,399.980011,-1.80,1,399.980011,299.989990,-539.969971,Western Europe,Overijssel,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,6/18/2015 17:38,First Class
16704,CASH,6,2,-246.500000,139.500000,Late delivery,1,24,Women's Apparel,Peabody,EE. UU.,XXXXXXXXX,Walter,2530,Smith,XXXXXXXXX,Consumer,MA,2291 Velvet Berry Freeway,1960.0,5,Golf,42.541645,-70.979378,LATAM,Presidencia Roque Sáenz Peña,Argentina,2530,3/30/2015 7:14,6050,502,10.50,0.07,15089,50.000000,-1.77,3,150.000000,139.500000,-246.500000,South America,Chaco,CLOSED,NaN,502,24,NaN,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,4/5/2015 7:14,Second Class
82311,DEBIT,4,4,60.189999,122.839996,Shipping on time,0,18,Men's Footwear,Santa Cruz,EE. UU.,XXXXXXXXX,Mary,7445,Smith,XXXXXXXXX,Consumer,CA,7342 Hidden Walk,95060.0,4,Apparel,36.970512,-122.023827,Europe,Villach,Austria,7445,6/28/2017 9:24,62298,403,7.15,0.06,155755,129.990005,0.49,1,129.990005,122.839996,60.189999,Western Europe,Carintia,COMPLETE,NaN,403,18,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,7/2/2017 9:24,Standard Class
60010,DEBIT,3,4,-27.410000,128.690002,Advance shipping,0,18,Men's Footwear,El Paso,EE. UU.,XXXXXXXXX,Mary,3406,Smith,XXXXXXXXX,Corporate,TX,9126 Wishing Expressway,79927.0,4,Apparel,31.651741,-106.267624,LATAM,São Paulo,Brasil,3406,1/26/2017 12:57,51827,403,1.30,0.01,129486,129.990005,-0.21,1,129.990005,128.690002,-27.410000,South America,São Paulo,COMPLETE,NaN,403,18,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,1/29/2017 12:57,Standard Class

In [141]:
# Convertimos la columna al formato datetime correcto
df_data['order_date_dateorders'] = pd.to_datetime(df_data['order_date_dateorders'])

In [142]:
# Esto te devolverá ambas fechas en una sola salida limpia

df_data['order_date_dateorders'].agg(['min', 'max'])

min   2015-01-01 00:00:00
max   2018-01-31 23:38:00
Name: order_date_dateorders, dtype: datetime64[us]

#### Eliminar columnas

In [143]:
df_data.drop(columns=["product_status", "customer_email", "customer_password", "product_description", "order_zipcode", "market", "order_state","product_image"],inplace=True)

#### Cambiar los códigos por abreviaturas del estado

In [144]:
dicc_ca = {"95758" : "CA", "91732" : "CA"}

df_data["customer_state"] = df_data["customer_state"].map(dicc_ca).fillna(df_data["customer_state"])

In [145]:
df_data["customer_state"].unique()

<StringArray>
['PR', 'CA', 'NY', 'FL', 'MA', 'IL', 'MT', 'PA', 'MI', 'TX', 'DE', 'GA', 'MD',
 'OH', 'HI', 'NJ', 'WI', 'AZ', 'CO', 'MN', 'NC', 'NM', 'OR', 'SC', 'VA', 'UT',
 'WA', 'KY', 'WV', 'RI', 'CT', 'LA', 'TN', 'DC', 'ND', 'MO', 'IN', 'ID', 'NV',
 'KS', 'AR', 'OK', 'AL', 'IA']
Length: 44, dtype: str

#### Convertir tipos de datos

In [146]:
df_data["customer_zipcode"] = df_data["customer_zipcode"].astype(str).str.replace(".0", "", regex=False)

In [147]:
df_data["order_item_discount"] = df_data["order_item_discount"].astype(float)

#### Rellenar los 3 nulos de la columna customer_zipcode usando la latitud y la longitud

In [148]:
# 1

df_data.loc[np.isclose(df_data["latitude"], 39.134159) & np.isclose(df_data["longitude"], -123.718552),"customer_zipcode"] = "95410"
 
# 2

df_data.loc[np.isclose(df_data["latitude"], 38.408573) & np.isclose(df_data["longitude"], -121.449112),"customer_zipcode"] = "95823"
 
# 3

df_data.loc[np.isclose(df_data["latitude"], 34.071892) & np.isclose(df_data["longitude"], -118.013886),"customer_zipcode"] = "91732"

#### Aplicar función para redondear los decimales

In [149]:
t.round_up(df_data)

df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class

#### Dividir una columna en dos, fecha y hora y cambiar el formato

In [150]:
df_data[['date', 'datetime']] = df_data['shipping_date_dateorders'].str.split(' ', expand=True)

In [151]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class,2/3/2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class,1/18/2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class,1/17/2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class,1/16/2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class,1/15/2018,11:24

In [152]:
df_data.drop(columns=["shipping_date_dateorders"],inplace=True)

In [153]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,2/3/2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,1/18/2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,1/17/2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,1/16/2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,1/15/2018,11:24

In [154]:
# Convertimos la columna al formato datetime correcto
df_data["date"] = pd.to_datetime(df_data["date"]).dt.strftime("%m-%d-%Y")
df_data["datetime"] = pd.to_timedelta(df_data["datetime"] + ":00").astype(str).str[-8:-3]

In [155]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,02-03-2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,01-18-2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,01-17-2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,01-16-2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,01-15-2018,11:24

#### Rellenar los nulos de la columna customer_lname por unknown

In [156]:
df_data["customer_lname"] = df_data["customer_lname"].fillna("Unknown")

In [157]:
df_data["customer_lname"].isna().sum()

np.int64(0)

In [158]:
df_data.to_csv("../files/processed/dataco_supply_chain.csv")

## ETL del dataset token

#### ver duplicados

In [179]:
df_token = pd.read_csv("../files/raw/tokenized_access_logs.csv")

In [180]:
df_token[df_token.duplicated(keep=False)].value_counts()

Product                                  Category              Date             Month  Hour  Department  ip              url
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        9/14/2017 20:31  Sep    20    apparel     147.29.196.147  /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            5
O'Brien Men's Neoprene Life Vest         indoor outdoor games  9/14/2017 11:20  Sep    11    fan shop    202.226.31.11   /department/fan%20shop/category/indoor/outdoor%20games/product/O'Brien%20Men's%20Neoprene%20Life%20Vest                4
Nike Men's Free TR 5.0 TB Training Shoe  as seen on  tv!       9/14/2017 12:28  Sep    12    footwear    138.45.174.221  /department/footwear/category/as%20seen%20on%20%20tv!/product/Nike%20Men's%20Free%20TR%205.0%20TB%20Training%20Shoe    4
Nike Men's Fingertrap Max Training Shoe  soccer                9/14/2017 18:09  Sep    18    fitness     10.184.28.55    /department/fitness/category/soccer/product/Nike%20Men's%20Fingertrap%20Max%20Training%20Shoe                          4
Nike Men's Dri-FIT Victory Golf Polo     women's apparel       9/14/2017 19:15  Sep    19    golf        36.85.174.235   /department/golf/category/women's%20apparel/product/Nike%20Men's%20Dri-FIT%20Victory%20Golf%20Polo                     4
                                                                                                                                                                                                                                               ..
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        10/6/2017 8:12   Oct    8     apparel     58.20.180.169   /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            2
TYR Boys' Team Digi Jammer               girls' apparel        10/6/2017 12:17  Oct    12    golf        194.22.243.107  /department/golf/category/girls'%20apparel/product/TYR%20Boys'%20Team%20Digi%20Jammer                                  2
Perfect Fitness Perfect Rip Deck         cleats                10/7/2017 20:48  Oct    20    apparel     95.234.113.98   /department/apparel/category/cleats/product/Perfect%20Fitness%20Perfect%20Rip%20Deck                                   2
Nike Men's Dri-FIT Victory Golf Polo     women's apparel       10/7/2017 21:40  Oct    21    golf        34.175.52.9     /department/golf/category/women's%20apparel/product/Nike%20Men's%20Dri-FIT%20Victory%20Golf%20Polo                     2
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        10/9/2017 12:56  Oct    12    apparel     105.58.81.244   /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            2
Name: count, Length: 3046, dtype: int64

#### Borrar duplicados

In [182]:
df_token.drop_duplicates(inplace=True)

In [183]:
df_token.duplicated().sum()

np.int64(0)

#### Borrar columnas

In [185]:
df_token.columns

Index(['Product', 'Category', 'Date', 'Month', 'Hour', 'Department', 'ip',
       'url'],
      dtype='str')

In [186]:
df_token = df_token.drop(['Month', 'Hour', 'url'], axis=1)

In [187]:
df_token.columns

Index(['Product', 'Category', 'Date', 'Department', 'ip'], dtype='str')

In [188]:
df_token.head()

,Product,Category,Date,Department,ip
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242

#### Estandarizar nombres columnas

In [190]:
df_token = t.standardize_columns(df_token)

In [191]:
df_token.head()

,product,category,date,department,ip
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242

#### Dividir una columna en dos, fecha y hora y cambiar el formato

In [193]:
df_token[['date2', 'datetime']] = df_token['date'].str.split(' ', expand=True)

In [195]:
df_token.head()

,product,category,date,department,ip,date2,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242,9/1/2017,6:01

In [196]:
df_token.drop(columns='date',inplace=True)

In [198]:
df_token.head()

,product,category,department,ip,date2,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,9/1/2017,6:01

In [199]:
df_token.rename(columns={'date2':'date'}, inplace=True)

In [201]:
df_token.head()

,product,category,department,ip,date,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,9/1/2017,6:01

In [203]:
# Convertimos la columna al formato datetime correcto
df_token["date"] = pd.to_datetime(df_token["date"]).dt.strftime("%m-%d-%Y")
df_token["datetime"] = pd.to_timedelta(df_token["datetime"] + ":00").astype(str).str[-8:-3]

In [204]:
df_token.head()

,product,category,department,ip,date,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,09-01-2017,06:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,09-01-2017,06:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,09-01-2017,06:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,09-01-2017,06:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,09-01-2017,06:01