In [127]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
sys.path.append(os.path.abspath(os.path.join('..')))
import src.exploration as e
import src.transform as t

In [128]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [129]:
df_data = pd.read_csv("../files/raw/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [130]:
df_data = t.standardize_columns(df_data)

In [131]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_email,customer_fname,customer_id,customer_lname,customer_password,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,market,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
73154,DEBIT,2,4,51.330002,163.990005,Advance shipping,0,48,Water Sports,Caguas,Puerto Rico,XXXXXXXXX,Lori,3059,Hensley,XXXXXXXXX,Corporate,PR,4429 Clear Panda Cove,725.0,7,Fan Shop,18.200169,-66.370522,Africa,Agadir,Marruecos,3059,12/21/2016 0:44,49326,1073,36.00,0.18,123308,199.990005,0.31,1,199.990005,163.990005,51.330002,North Africa,Sus-Masa-Draa,COMPLETE,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,12/23/2016 0:44,Standard Class
59735,DEBIT,5,4,93.500000,339.980011,Late delivery,1,45,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Adam,5266,Pratt,XXXXXXXXX,Corporate,NY,3193 Old Parkway,11219.0,7,Fan Shop,40.634663,-73.994804,Europe,Trento,Italia,5266,8/25/2015 16:08,16214,1004,60.00,0.15,40474,399.980011,0.28,1,399.980011,339.980011,93.500000,Southern Europe,Trentino-Alto Adigio,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,8/30/2015 16:08,Standard Class
65506,DEBIT,5,2,48.139999,165.979996,Late delivery,1,9,Cardio Equipment,Long Beach,EE. UU.,XXXXXXXXX,Laura,11262,Lopez,XXXXXXXXX,Consumer,CA,2 Middle Mall,90805.0,3,Footwear,33.767063,-118.189255,Europe,Galati,Rumania,11262,11/29/2016 18:17,47869,191,34.00,0.17,119700,99.989998,0.29,2,199.979996,165.979996,48.139999,Eastern Europe,Galati,COMPLETE,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,12/4/2016 18:17,Second Class
114530,TRANSFER,5,4,-468.559998,187.429993,Late delivery,1,46,Indoor/Outdoor Games,East Brunswick,EE. UU.,XXXXXXXXX,Lauren,10281,Smith,XXXXXXXXX,Consumer,NJ,2770 Hidden Villas,8816.0,7,Fan Shop,40.412552,-74.418327,LATAM,Santana de Parnaíba,Brasil,10281,1/21/2015 4:31,1384,1014,62.48,0.25,3420,49.980000,-2.50,5,249.899994,187.429993,-468.559998,South America,São Paulo,PENDING,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,1/26/2015 4:31,Standard Class
81013,DEBIT,5,4,52.380001,193.990005,Late delivery,1,48,Water Sports,Simi Valley,EE. UU.,XXXXXXXXX,Julia,4794,Mosley,XXXXXXXXX,Consumer,CA,7832 Wishing Court,93063.0,7,Fan Shop,34.267914,-118.671211,Pacific Asia,Ipoh,Malasia,4794,1/31/2016 20:38,27119,1073,6.00,0.03,67941,199.990005,0.27,1,199.990005,193.990005,52.380001,Southeast Asia,Perak,COMPLETE,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,2/5/2016 20:38,Standard Class

In [132]:
# Convertimos la columna al formato datetime correcto
df_data['order_date_dateorders'] = pd.to_datetime(df_data['order_date_dateorders'])

In [133]:
# Esto te devolverá ambas fechas en una sola salida limpia

df_data['order_date_dateorders'].agg(['min', 'max'])

min   2015-01-01 00:00:00
max   2018-01-31 23:38:00
Name: order_date_dateorders, dtype: datetime64[us]

#### Eliminar columnas

In [134]:
df_data.drop(columns=["product_status", "customer_email", "customer_password", "product_description", "order_zipcode", "market", "order_state","product_image"],inplace=True)

#### Cambiar los códigos por abreviaturas del estado

In [135]:
dicc_ca = {"95758" : "CA", "91732" : "CA"}

df_data["customer_state"] = df_data["customer_state"].map(dicc_ca).fillna(df_data["customer_state"])

In [136]:
df_data["customer_state"].unique()

<StringArray>
['PR', 'CA', 'NY', 'FL', 'MA', 'IL', 'MT', 'PA', 'MI', 'TX', 'DE', 'GA', 'MD',
 'OH', 'HI', 'NJ', 'WI', 'AZ', 'CO', 'MN', 'NC', 'NM', 'OR', 'SC', 'VA', 'UT',
 'WA', 'KY', 'WV', 'RI', 'CT', 'LA', 'TN', 'DC', 'ND', 'MO', 'IN', 'ID', 'NV',
 'KS', 'AR', 'OK', 'AL', 'IA']
Length: 44, dtype: str

#### Convertir tipos de datos

In [137]:
df_data["customer_zipcode"] = df_data["customer_zipcode"].astype(str).str.replace(".0", "", regex=False)

In [138]:
df_data["order_item_discount"] = df_data["order_item_discount"].astype(float)

#### Rellenar los 3 nulos de la columna customer_zipcode usando la latitud y la longitud

In [139]:
# 1

df_data.loc[np.isclose(df_data["latitude"], 39.134159) & np.isclose(df_data["longitude"], -123.718552),"customer_zipcode"] = "95410"
 
# 2

df_data.loc[np.isclose(df_data["latitude"], 38.408573) & np.isclose(df_data["longitude"], -121.449112),"customer_zipcode"] = "95823"
 
# 3

df_data.loc[np.isclose(df_data["latitude"], 34.071892) & np.isclose(df_data["longitude"], -118.013886),"customer_zipcode"] = "91732"

#### Aplicar función para redondear los decimales

In [140]:
t.round_up(df_data)

df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class

#### Dividir una columna en dos, fecha y hora y cambiar el formato

In [141]:
df_data[['date', 'datetime']] = df_data['shipping_date_dateorders'].str.split(' ', expand=True)

In [142]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class,2/3/2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class,1/18/2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class,1/17/2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class,1/16/2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class,1/15/2018,11:24

In [143]:
df_data.drop(columns=["shipping_date_dateorders"],inplace=True)

In [144]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,2/3/2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,1/18/2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,1/17/2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,1/16/2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,1/15/2018,11:24

In [145]:
# Convertimos la columna al formato datetime correcto
df_data["date"] = pd.to_datetime(df_data["date"]).dt.strftime("%m-%d-%Y")
df_data["datetime"] = pd.to_timedelta(df_data["datetime"] + ":00").astype(str).str[-8:-3]

In [146]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,date,datetime
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,02-03-2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,01-18-2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,01-17-2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,01-16-2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,01-15-2018,11:24

#### Rellenar los nulos de la columna customer_lname por unknown

In [148]:
df_data["customer_lname"] = df_data["customer_lname"].fillna("Unknown")

In [151]:
df_data["customer_lname"].isna().sum()

np.int64(0)

## ETL del dataset token

#### ver duplicados