In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
import sys
import os # Esto sube un nivel en las carpetas para encontrar la raíz del proyecto
sys.path.append(os.path.abspath(os.path.join('..')))
import src.exploration as e
import src.transform as t

In [3]:
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [4]:
df_data = pd.read_csv("../files/raw/dataco_supply_chain.csv", sep=None, engine="python", encoding="latin-1")

In [5]:
df_data = t.standardize_columns(df_data)

In [6]:
df_data.sample(5)

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_email,customer_fname,customer_id,customer_lname,customer_password,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,market,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,order_zipcode,product_card_id,product_category_id,product_description,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
150214,DEBIT,2,4,14.400000,143.960007,Advance shipping,0,29,Shop By Sport,Caguas,Puerto Rico,XXXXXXXXX,Madison,3188,Ray,XXXXXXXXX,Home Office,PR,9276 Jagged Towers,725.0,5,Golf,18.297707,-66.370560,USCA,San Francisco,Estados Unidos,3188,7/11/2016 23:55,38226,627,16.0,0.10,95424,39.990002,0.10,4,159.960007,143.960007,14.400000,West of USA,California,COMPLETE,94109.0,627,29,NaN,http://images.acmesports.sports/Under+Armour+G...,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,7/13/2016 23:55,Standard Class
169298,TRANSFER,2,2,32.529999,118.290001,Shipping canceled,0,18,Men's Footwear,West Jordan,EE. UU.,XXXXXXXXX,Ann,6490,Smith,XXXXXXXXX,Home Office,UT,9938 Noble Woods,84084.0,4,Apparel,40.621956,-111.933273,Europe,Uvarovo,Rusia,6490,11/15/2016 1:08,46861,403,11.7,0.09,117146,129.990005,0.28,1,129.990005,118.290001,32.529999,Eastern Europe,Tambov,SUSPECTED_FRAUD,NaN,403,18,NaN,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,11/17/2016 1:08,Second Class
128126,DEBIT,3,4,56.959999,181.979996,Advance shipping,0,9,Cardio Equipment,Corona,EE. UU.,XXXXXXXXX,Mary,5107,Waters,XXXXXXXXX,Consumer,CA,3152 Wishing Limits,92879.0,3,Footwear,33.927589,-117.545563,USCA,Los Angeles,Estados Unidos,5107,6/20/2016 4:30,36732,191,18.0,0.09,91658,99.989998,0.31,2,199.979996,181.979996,56.959999,West of USA,California,COMPLETE,90008.0,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,6/23/2016 4:30,Standard Class
77121,CASH,2,2,2.250000,44.980000,Shipping on time,0,46,Indoor/Outdoor Games,New Orleans,EE. UU.,XXXXXXXXX,Mary,11730,Perkins,XXXXXXXXX,Corporate,LA,37 Lost Hills Maze,70117.0,7,Fan Shop,29.967743,-90.034943,Europe,Le Blanc-Mesnil,Francia,11730,9/28/2017 13:08,68611,1014,5.0,0.10,171532,49.980000,0.05,1,49.980000,44.980000,2.250000,Western Europe,Isla de Francia,CLOSED,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,9/30/2017 13:08,Second Class
137268,TRANSFER,6,4,40.680000,359.980011,Late delivery,1,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Jordan,4320,Taylor,XXXXXXXXX,Consumer,PR,7192 Green Arbor,725.0,7,Fan Shop,18.208479,-66.370605,LATAM,Aracaju,Brasil,4320,6/8/2017 4:53,60915,1004,40.0,0.10,152411,399.980011,0.11,1,399.980011,359.980011,40.680000,South America,Sergipe,PENDING,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,6/14/2017 4:53,Standard Class

#### Eliminar columnas

In [7]:
df_data.drop(columns=["product_status", "customer_email", "customer_password", "product_description", "order_zipcode", "market", "order_state","product_image"],inplace=True)

#### Cambiar los códigos por abreviaturas del estado

In [8]:
dicc_ca = {"95758" : "CA", "91732" : "CA"}

df_data["customer_state"] = df_data["customer_state"].map(dicc_ca).fillna(df_data["customer_state"])

In [9]:
df_data["customer_state"].unique()

<StringArray>
['PR', 'CA', 'NY', 'FL', 'MA', 'IL', 'MT', 'PA', 'MI', 'TX', 'DE', 'GA', 'MD',
 'OH', 'HI', 'NJ', 'WI', 'AZ', 'CO', 'MN', 'NC', 'NM', 'OR', 'SC', 'VA', 'UT',
 'WA', 'KY', 'WV', 'RI', 'CT', 'LA', 'TN', 'DC', 'ND', 'MO', 'IN', 'ID', 'NV',
 'KS', 'AR', 'OK', 'AL', 'IA']
Length: 44, dtype: str

#### Cambiar las abreviaturas por el nombre del estado

In [10]:
state_mapping = {
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia'
}

In [11]:
df_data["customer_state"] = df_data["customer_state"].map(state_mapping)

#### Convertir tipos de datos

In [12]:
df_data["customer_zipcode"] = df_data["customer_zipcode"].astype(str).str.replace(".0", "", regex=False)

In [13]:
df_data["order_item_discount"] = df_data["order_item_discount"].astype(float)

#### Rellenar los 3 nulos de la columna customer_zipcode usando la latitud y la longitud

In [14]:
# 1

df_data.loc[np.isclose(df_data["latitude"], 39.134159) & np.isclose(df_data["longitude"], -123.718552),"customer_zipcode"] = "95410"
 
# 2

df_data.loc[np.isclose(df_data["latitude"], 38.408573) & np.isclose(df_data["longitude"], -121.449112),"customer_zipcode"] = "95823"
 
# 3

df_data.loc[np.isclose(df_data["latitude"], 34.071892) & np.isclose(df_data["longitude"], -118.013886),"customer_zipcode"] = "91732"

#### Aplicar función para redondear los decimales

In [15]:
t.round_up(df_data)

df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,Puerto Rico,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,Puerto Rico,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,California,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,California,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,Puerto Rico,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class

#### Dividir una columna en dos, fecha y hora y cambiar el formato

In [16]:
df_data['delivery_date'] = df_data['shipping_date_dateorders'].str.split(' ').str[0]

In [17]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode,delivery_date
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,Puerto Rico,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class,2/3/2018
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,Puerto Rico,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class,1/18/2018
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,California,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class,1/17/2018
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,California,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class,1/16/2018
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,Puerto Rico,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class,1/15/2018

In [18]:
df_data.drop(columns=["shipping_date_dateorders"],inplace=True)

In [19]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,Puerto Rico,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,2/3/2018
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,Puerto Rico,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,1/18/2018
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,California,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,1/17/2018
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,California,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,1/16/2018
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,Puerto Rico,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,1/15/2018

In [20]:
# Convertimos la columna al formato datetime correcto
df_data["delivery_date"] = pd.to_datetime(df_data["delivery_date"]).dt.strftime("%m-%d-%Y")

In [21]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,Puerto Rico,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,02-03-2018
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,Puerto Rico,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,01-18-2018
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,California,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,01-17-2018
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,California,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,01-16-2018
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,Puerto Rico,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,01-15-2018

In [22]:
df_data[['order_date', 'order_time']] = df_data['order_date_dateorders'].str.split(' ', expand=True)

In [23]:
df_data.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_fname,customer_id,customer_lname,customer_segment,customer_state,customer_street,customer_zipcode,department_id,department_name,latitude,longitude,order_city,order_country,order_customer_id,order_date_dateorders,order_id,order_item_cardprod_id,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_card_id,product_category_id,product_name,product_price,shipping_mode,delivery_date,order_date,order_time
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,Puerto Rico,5365 Noble Nectar Island,725,2,Fitness,18.251453,-66.037056,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.11,0.04,180517,327.75,0.29,1,327.75,314.64,91.25,Southeast Asia,COMPLETE,1360,73,Smart watch,327.75,Standard Class,02-03-2018,1/31/2018,22:56
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,Puerto Rico,2679 Rustic Loop,725,2,Fitness,18.279451,-66.037064,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.39,0.05,179254,327.75,-0.80,1,327.75,311.36,-249.09,South Asia,PENDING,1360,73,Smart watch,327.75,Standard Class,01-18-2018,1/13/2018,12:27
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,California,8510 Round Bear Gate,95125,2,Fitness,37.292233,-121.881279,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.03,0.06,179253,327.75,-0.80,1,327.75,309.72,-247.78,South Asia,CLOSED,1360,73,Smart watch,327.75,Standard Class,01-17-2018,1/13/2018,12:06
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,California,3200 Amber Bend,90027,2,Fitness,34.125946,-118.291016,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.94,0.07,179252,327.75,0.08,1,327.75,304.81,22.86,Oceania,COMPLETE,1360,73,Smart watch,327.75,Standard Class,01-16-2018,1/13/2018,11:45
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,Puerto Rico,8671 Iron Anchor Corners,725,2,Fitness,18.253769,-66.037048,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.50,0.09,179251,327.75,0.45,1,327.75,298.25,134.21,Oceania,PENDING_PAYMENT,1360,73,Smart watch,327.75,Standard Class,01-15-2018,1/13/2018,11:24

In [24]:
df_data.drop(columns=['order_date_dateorders'],inplace=True)
df_data.drop(columns=['latitude', 'longitude'],inplace=True)

Cambios formatos de hora

In [25]:
# Convertimos la columna al formato datetime correcto
df_data["order_date"] = pd.to_datetime(df_data["order_date"]).dt.strftime("%m-%d-%Y")
df_data["order_time"] = pd.to_timedelta(df_data["order_time"] + ":00").astype(str).str[-8:-3]

#### Rellenar los nulos de la columna customer_lname por unknown

In [26]:
df_data["customer_lname"] = df_data["customer_lname"].fillna("Unknown")

In [27]:
df_data["customer_lname"].isna().sum()

np.int64(0)

Cambio de formato columnas de país

In [28]:
df_data["order_country"] = df_data["order_country"].str.lower()

In [29]:
sorted(df_data["order_country"].unique().tolist())

['afganistán',
 'albania',
 'alemania',
 'angola',
 'arabia saudí',
 'argelia',
 'argentina',
 'armenia',
 'australia',
 'austria',
 'azerbaiyán',
 'bangladés',
 'barbados',
 'baréin',
 'belice',
 'benín',
 'bielorrusia',
 'bolivia',
 'bosnia y herzegovina',
 'botsuana',
 'brasil',
 'bulgaria',
 'burkina faso',
 'burundi',
 'bután',
 'bélgica',
 'camboya',
 'camerún',
 'canada',
 'chad',
 'chile',
 'china',
 'chipre',
 'colombia',
 'corea del sur',
 'costa de marfil',
 'costa rica',
 'croacia',
 'cuba',
 'dinamarca',
 'ecuador',
 'egipto',
 'el salvador',
 'emiratos árabes unidos',
 'eritrea',
 'eslovaquia',
 'eslovenia',
 'españa',
 'estados unidos',
 'estonia',
 'etiopía',
 'filipinas',
 'finlandia',
 'francia',
 'gabón',
 'georgia',
 'ghana',
 'grecia',
 'guadalupe',
 'guatemala',
 'guayana francesa',
 'guinea',
 'guinea ecuatorial',
 'guinea-bissau',
 'guyana',
 'haití',
 'honduras',
 'hong kong',
 'hungría',
 'india',
 'indonesia',
 'irak',
 'irlanda',
 'irán',
 'israel',
 'italia',
 'jamaica',
 'japón',
 'jordania',
 'kazajistán',
 'kenia',
 'kirguistán',
 'kuwait',
 'laos',
 'lesoto',
 'liberia',
 'libia',
 'lituania',
 'luxemburgo',
 'líbano',
 'macedonia',
 'madagascar',
 'malasia',
 'mali',
 'marruecos',
 'martinica',
 'mauritania',
 'moldavia',
 'mongolia',
 'montenegro',
 'mozambique',
 'myanmar (birmania)',
 'méxico',
 'namibia',
 'nepal',
 'nicaragua',
 'nigeria',
 'noruega',
 'nueva zelanda',
 'níger',
 'omán',
 'pakistán',
 'panamá',
 'papúa nueva guinea',
 'paraguay',
 'países bajos',
 'perú',
 'polonia',
 'portugal',
 'qatar',
 'reino unido',
 'república centroafricana',
 'república checa',
 'república de gambia',
 'república del congo',
 'república democrática del congo',
 'república dominicana',
 'ruanda',
 'rumania',
 'rusia',
 'senegal',
 'serbia',
 'sierra leona',
 'singapur',
 'siria',
 'somalia',
 'sri lanka',
 'suazilandia',
 'sudafrica',
 'sudán',
 'sudán del sur',
 'suecia',
 'suiza',
 'surinam',
 'sáhara occidental',
 'tailandia',
 'taiwán',
 'tanzania',
 'tayikistán',
 'togo',
 'trinidad y tobago',
 'turkmenistán',
 'turquía',
 'túnez',
 'ucrania',
 'uganda',
 'uruguay',
 'uzbekistán',
 'venezuela',
 'vietnam',
 'yemen',
 'yibuti',
 'zambia',
 'zimbabue']

In [30]:
df_data["order_country"] = df_data["order_country"].str.title()

In [31]:
sorted(df_data["order_country"].unique().tolist())

['Afganistán',
 'Albania',
 'Alemania',
 'Angola',
 'Arabia Saudí',
 'Argelia',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaiyán',
 'Bangladés',
 'Barbados',
 'Baréin',
 'Belice',
 'Benín',
 'Bielorrusia',
 'Bolivia',
 'Bosnia Y Herzegovina',
 'Botsuana',
 'Brasil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Bután',
 'Bélgica',
 'Camboya',
 'Camerún',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Chipre',
 'Colombia',
 'Corea Del Sur',
 'Costa De Marfil',
 'Costa Rica',
 'Croacia',
 'Cuba',
 'Dinamarca',
 'Ecuador',
 'Egipto',
 'El Salvador',
 'Emiratos Árabes Unidos',
 'Eritrea',
 'Eslovaquia',
 'Eslovenia',
 'España',
 'Estados Unidos',
 'Estonia',
 'Etiopía',
 'Filipinas',
 'Finlandia',
 'Francia',
 'Gabón',
 'Georgia',
 'Ghana',
 'Grecia',
 'Guadalupe',
 'Guatemala',
 'Guayana Francesa',
 'Guinea',
 'Guinea Ecuatorial',
 'Guinea-Bissau',
 'Guyana',
 'Haití',
 'Honduras',
 'Hong Kong',
 'Hungría',
 'India',
 'Indonesia',
 'Irak',
 'Irlanda',
 'Irán',
 'Israel',
 'Italia',
 'Jamaica',
 'Japón',
 'Jordania',
 'Kazajistán',
 'Kenia',
 'Kirguistán',
 'Kuwait',
 'Laos',
 'Lesoto',
 'Liberia',
 'Libia',
 'Lituania',
 'Luxemburgo',
 'Líbano',
 'Macedonia',
 'Madagascar',
 'Malasia',
 'Mali',
 'Marruecos',
 'Martinica',
 'Mauritania',
 'Moldavia',
 'Mongolia',
 'Montenegro',
 'Mozambique',
 'Myanmar (Birmania)',
 'México',
 'Namibia',
 'Nepal',
 'Nicaragua',
 'Nigeria',
 'Noruega',
 'Nueva Zelanda',
 'Níger',
 'Omán',
 'Pakistán',
 'Panamá',
 'Papúa Nueva Guinea',
 'Paraguay',
 'Países Bajos',
 'Perú',
 'Polonia',
 'Portugal',
 'Qatar',
 'Reino Unido',
 'República Centroafricana',
 'República Checa',
 'República De Gambia',
 'República Del Congo',
 'República Democrática Del Congo',
 'República Dominicana',
 'Ruanda',
 'Rumania',
 'Rusia',
 'Senegal',
 'Serbia',
 'Sierra Leona',
 'Singapur',
 'Siria',
 'Somalia',
 'Sri Lanka',
 'Suazilandia',
 'Sudafrica',
 'Sudán',
 'Sudán Del Sur',
 'Suecia',
 'Suiza',
 'Surinam',
 'Sáhara Occidental',
 'Tailandia',
 'Taiwán',
 'Tanzania',
 'Tayikistán',
 'Togo',
 'Trinidad Y Tobago',
 'Turkmenistán',
 'Turquía',
 'Túnez',
 'Ucrania',
 'Uganda',
 'Uruguay',
 'Uzbekistán',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Yibuti',
 'Zambia',
 'Zimbabue']

In [32]:
df_data.to_csv("../files/processed/dataco_supply_chain.csv", index=False)

## ETL del dataset token

#### ver duplicados

In [33]:
df_token = pd.read_csv("../files/raw/tokenized_access_logs.csv")

In [34]:
df_token[df_token.duplicated(keep=False)].value_counts()

Product                                  Category              Date             Month  Hour  Department  ip              url
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        9/14/2017 20:31  Sep    20    apparel     147.29.196.147  /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            5
O'Brien Men's Neoprene Life Vest         indoor outdoor games  9/14/2017 11:20  Sep    11    fan shop    202.226.31.11   /department/fan%20shop/category/indoor/outdoor%20games/product/O'Brien%20Men's%20Neoprene%20Life%20Vest                4
Nike Men's Free TR 5.0 TB Training Shoe  as seen on  tv!       9/14/2017 12:28  Sep    12    footwear    138.45.174.221  /department/footwear/category/as%20seen%20on%20%20tv!/product/Nike%20Men's%20Free%20TR%205.0%20TB%20Training%20Shoe    4
Nike Men's Fingertrap Max Training Shoe  soccer                9/14/2017 18:09  Sep    18    fitness     10.184.28.55    /department/fitness/category/soccer/product/Nike%20Men's%20Fingertrap%20Max%20Training%20Shoe                          4
Nike Men's Dri-FIT Victory Golf Polo     women's apparel       9/14/2017 19:15  Sep    19    golf        36.85.174.235   /department/golf/category/women's%20apparel/product/Nike%20Men's%20Dri-FIT%20Victory%20Golf%20Polo                     4
                                                                                                                                                                                                                                               ..
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        10/6/2017 8:12   Oct    8     apparel     58.20.180.169   /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            2
TYR Boys' Team Digi Jammer               girls' apparel        10/6/2017 12:17  Oct    12    golf        194.22.243.107  /department/golf/category/girls'%20apparel/product/TYR%20Boys'%20Team%20Digi%20Jammer                                  2
Perfect Fitness Perfect Rip Deck         cleats                10/7/2017 20:48  Oct    20    apparel     95.234.113.98   /department/apparel/category/cleats/product/Perfect%20Fitness%20Perfect%20Rip%20Deck                                   2
Nike Men's Dri-FIT Victory Golf Polo     women's apparel       10/7/2017 21:40  Oct    21    golf        34.175.52.9     /department/golf/category/women's%20apparel/product/Nike%20Men's%20Dri-FIT%20Victory%20Golf%20Polo                     2
Nike Men's CJ Elite 2 TD Football Cleat  men's footwear        10/9/2017 12:56  Oct    12    apparel     105.58.81.244   /department/apparel/category/men's%20footwear/product/Nike%20Men's%20CJ%20Elite%202%20TD%20Football%20Cleat            2
Name: count, Length: 3046, dtype: int64

#### Borrar duplicados

In [35]:
df_token.drop_duplicates(inplace=True)

In [36]:
df_token.duplicated().sum()

np.int64(0)

#### Borrar columnas

In [37]:
df_token.columns

Index(['Product', 'Category', 'Date', 'Month', 'Hour', 'Department', 'ip',
       'url'],
      dtype='str')

In [38]:
df_token = df_token.drop(['Month', 'Hour', 'url'], axis=1)

In [39]:
df_token.columns

Index(['Product', 'Category', 'Date', 'Department', 'ip'], dtype='str')

In [40]:
df_token.head()

,Product,Category,Date,Department,ip
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242

#### Estandarizar nombres columnas

In [41]:
df_token = t.standardize_columns(df_token)

In [42]:
df_token.head()

,product,category,date,department,ip
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242

#### Dividir una columna en dos, fecha y hora y cambiar el formato

In [43]:
df_token[['date2', 'datetime']] = df_token['date'].str.split(' ', expand=True)

In [44]:
df_token.head()

,product,category,date,department,ip,date2,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,fan shop,136.108.56.242,9/1/2017,6:01

In [45]:
df_token.drop(columns='date',inplace=True)

In [46]:
df_token.head()

,product,category,department,ip,date2,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,9/1/2017,6:01

In [47]:
df_token.rename(columns={'date2':'date'}, inplace=True)

In [48]:
df_token.head()

,product,category,department,ip,date,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,9/1/2017,6:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,9/1/2017,6:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,9/1/2017,6:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,9/1/2017,6:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,9/1/2017,6:01

In [49]:
# Convertimos la columna al formato datetime correcto
df_token["date"] = pd.to_datetime(df_token["date"]).dt.strftime("%m-%d-%Y")
df_token["datetime"] = pd.to_timedelta(df_token["datetime"] + ":00").astype(str).str[-8:-3]

In [50]:
df_token.head()

,product,category,department,ip,date,datetime
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,fitness,37.97.182.65,09-01-2017,06:00
1,The North Face Women's Recon Backpack,hunting & shooting,fan shop,206.56.112.1,09-01-2017,06:00
2,adidas Kids' RG III Mid Football Cleat,featured shops,apparel,215.143.180.0,09-01-2017,06:00
3,Under Armour Men's Compression EV SL Slide,electronics,footwear,206.56.112.1,09-01-2017,06:00
4,Pelican Sunstream 100 Kayak,water sports,fan shop,136.108.56.242,09-01-2017,06:01

In [51]:
df_token.to_csv("../files/processed/token_access_logs.csv", index=False, encoding="utf-8")